# Generated by Django 2.1.7 on 2019-03-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(help_text='Enter a movie genre (e.g. Horror)', max_length=200, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Movie Description')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('actor', models.CharField(max_length=1000, verbose_name="Actors' Names")),
                ('link', models.URLField(verbose_name='Youtube Link')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Director')),
                ('genre_name', models.ManyToManyField(help_text='Select a genre for this movie ', to='catalog.Genre')),
            ],
        ),
    ]
