# Generated by Django 2.2 on 2019-04-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('lastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.CharField(max_length=50, verbose_name='E-Mail')),
                ('userName', models.CharField(max_length=200, verbose_name='User Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('CCVNumber', models.IntegerField(verbose_name='CCV Number')),
                ('expirationDate', models.DateField(verbose_name='Expiration Date')),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
    ]
