# Generated by Django 2.2 on 2019-05-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('lastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.CharField(max_length=50, verbose_name='E-Mail')),
                ('userName', models.CharField(max_length=200, verbose_name='User Name')),
                ('CCVNumber', models.IntegerField(verbose_name='CCV Number')),
                ('expirationDate', models.DateField(verbose_name='Expiration Date')),
                ('purchase_date', models.DateField(verbose_name='Date of Purchase')),
                ('sd_price', models.IntegerField(verbose_name='Price of SD Movie')),
                ('hd_price', models.IntegerField(verbose_name='Price of HD Movie')),
            ],
        ),
    ]
