# Generated by Django 2.2 on 2019-05-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hd_price',
            field=models.CharField(max_length=10, verbose_name='Price of HD Movie'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sd_price',
            field=models.CharField(max_length=10, verbose_name='Price of SD Movie'),
        ),
    ]
