# Generated by Django 2.2 on 2019-04-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('actors', models.CharField(max_length=1000, verbose_name='Actors')),
                ('director', models.CharField(max_length=200, verbose_name='Director')),
                ('link', models.URLField(verbose_name='Youtube Link')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('img', models.CharField(max_length=300, verbose_name='Image')),
                ('img_r', models.CharField(max_length=300, verbose_name='Image R')),
                ('hd_link', models.URLField(verbose_name='HD Link')),
            ],
        ),
    ]
