# Generated by Django 2.2 on 2019-05-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hd_price',
            field=models.IntegerField(null=True, verbose_name='Price of HD Movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='sd_price',
            field=models.IntegerField(null=True, verbose_name='Price of SD Movie'),
        ),
    ]
