# Generated by Django 2.2 on 2019-05-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190501_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='hd_price',
            field=models.CharField(max_length=10, verbose_name='Price of HD Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sd_price',
            field=models.CharField(max_length=10, verbose_name='Price of SD Movie'),
        ),
    ]
