# Generated by Django 2.2 on 2019-05-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190501_1856'),
        ('catalog', '0003_auto_20190501_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='transactionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Transaction', verbose_name='Transaction ID'),
        ),
    ]
