# Generated by Django 2.2 on 2019-04-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Movie Description')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('actor', models.CharField(max_length=1000, verbose_name="Actors' Names")),
                ('director', models.CharField(max_length=200, verbose_name='Director')),
                ('link', models.URLField(verbose_name='Youtube Link')),
                ('genre_name', models.CharField(max_length=100, verbose_name='Genre')),
            ],
        ),
    ]
